name: flutter_ui_challenges
description: "Flutter UI Challenges."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  readmore: ^3.0.0
  flutter_gen: ^5.10.0
  flutter_svg: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.15
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_gen:
  output: lib/utils/gen/
  line_length: 80

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coffee app
    - assets/icons/